#!/bin/sh
LATEST_JSON_RPC_RELAY_VERSION=$(curl --silent https://api.github.com/repos/hiero-ledger/hiero-json-rpc-relay/releases | jq -r '.[0].tag_name' | cut -c 2-)

docker run \
--rm \
-p 7546:7546 \
-e CHAIN_ID=296 \
-e HEDERA_NETWORK=testnet \
-e MIRROR_NODE_URL=https://testnet.mirrornode.hedera.com \
-e OPERATOR_ID_MAIN=$NATIVE_ACCOUNT_ID \
-e OPERATOR_KEY_MAIN=$NATIVE_PRIVATE_KEY \
-e REDIS_ENABLED=false \
-e CACHE_TTL=1 \
-e SDK_LOG_LEVEL=trace \
-e RATE_LIMIT_DISABLED=true \
ghcr.io/hiero-ledger/hiero-json-rpc-relay:$LATEST_JSON_RPC_RELAY_VERSION
